unbind C-b
set -g prefix C-b

# Simplify remote status bar
set -g status-left "#H:[#S]"
set -g status-right ""

# Place status bar on bottom (to avoid overlap with local session bar)
set-option -g status-position bottom
