import = ["~/.config/alacritty/themes/gruvbox.toml"]

[env]
term = "xterm-256color"

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
size = 12

[window]
padding = { x = 15, y = 10 }
decorations = "Buttonless"
opacity = 0.92
# blur = true
startup_mode = "Maximized"
