# Alacritty Configuration with Gruvbox theme, 80% transparency, and Cascadia Code font

# Window configuration
[window]
# Background opacity (0.0 = fully transparent, 1.0 = opaque)
opacity = 0.8

# Window padding
[window.padding]
x = 10
y = 10

# Font configuration
[font]
# Font size (in points)
size = 14.0

# Normal (roman) font face
[font.normal]
family = "Cascadia Code"
style = "Regular"

# Bold font face
[font.bold]
family = "Cascadia Code"
style = "Bold"

# Italic font face
[font.italic]
family = "Cascadia Code"
style = "Italic"

# Bold italic font face
[font.bold_italic]
family = "Cascadia Code"
style = "Bold Italic"

# Offset is the extra space around each character
[font.offset]
x = 0
y = 0

# Glyph offset determines the locations of the glyphs within their cells
[font.glyph_offset]
x = 0
y = 0

# Gruvbox dark theme colors
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

# Normal colors
[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

# Bright colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# Cursor style
[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

# Mouse settings
[mouse]
hide_when_typing = true

# Scrolling settings
[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling distance multiplier
multiplier = 3

# Terminal bell settings
[bell]
# Visual bell animation effect for flashing the screen when the visual bell is rung
animation = "EaseOutExpo"

# Duration of the visual bell flash in milliseconds
duration = 0

# Selection settings
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard
save_to_clipboard = true

